
import React from 'react';
import { GENERATED_DEMO_TEXTS } from './generatedDemoTexts';

export const CATEGORIES = [
  { id: 'hate_speech', label: 'Hate Speech', icon: <i className="fas fa-skull"></i> },
  { id: 'harassment', label: 'Harassment', icon: <i className="fas fa-hand-middle-finger"></i> },
  { id: 'profanity', label: 'Profanity', icon: <i className="fas fa-exclamation-triangle"></i> },
  { id: 'threat', label: 'Threat', icon: <i className="fas fa-bomb"></i> },
  { id: 'racism', label: 'Racism', icon: <i className="fas fa-users-slash"></i> },
  { id: 'bullying', label: 'Bullying', icon: <i className="fas fa-user-injured"></i> },
  { id: 'sexual_content', label: 'Sexual Content', icon: <i className="fas fa-venus-mars"></i> },
  { id: 'spam', label: 'Spamming', icon: <i className="fas fa-robot"></i> },
  { id: 'sarcasm', label: 'Sarcasm', icon: <i className="fas fa-smirk"></i> },
  { id: 'trash_talk', label: 'Trash Talk', icon: <i className="fas fa-comments"></i> },
];

export const LANGUAGES = [
  { value: 'auto', label: 'Auto Detect Language', flag: '🌍' },
  { value: 'af', label: 'Afrikaans', flag: '🇿🇦' },
  { value: 'sq', label: 'Albanian', flag: '🇦🇱' },
  { value: 'am', label: 'Amharic', flag: '🇪🇹' },
  { value: 'ar', label: 'Arabic', flag: '🇸🇦' },
  { value: 'hy', label: 'Armenian', flag: '🇦🇲' },
  { value: 'az', label: 'Azerbaijani', flag: '🇦🇿' },
  { value: 'eu', label: 'Basque', flag: '🇪🇸' },
  { value: 'be', label: 'Belarusian', flag: '🇧🇾' },
  { value: 'bn', label: 'Bengali', flag: '🇧🇩' },
  { value: 'bs', label: 'Bosnian', flag: '🇧🇦' },
  { value: 'bg', label: 'Bulgarian', flag: '🇧🇬' },
  { value: 'ca', label: 'Catalan', flag: '🇪🇸' },
  { value: 'ceb', label: 'Cebuano', flag: '🇵🇭' },
  { value: 'ny', label: 'Chichewa', flag: '🇲🇼' },
  { value: 'zh', label: 'Chinese', flag: '🇨🇳' },
  { value: 'co', label: 'Corsican', flag: '🇫🇷' },
  { value: 'hr', label: 'Croatian', flag: '🇭🇷' },
  { value: 'cs', label: 'Czech', flag: '🇨🇿' },
  { value: 'da', label: 'Danish', flag: '🇩🇰' },
  { value: 'nl', label: 'Dutch', flag: '🇳🇱' },
  { value: 'en', label: 'English', flag: '🇺🇸' },
  { value: 'eo', label: 'Esperanto', flag: '🏳️' },
  { value: 'et', label: 'Estonian', flag: '🇪🇪' },
  { value: 'tl', label: 'Filipino', flag: '🇵🇭' },
  { value: 'fi', label: 'Finnish', flag: '🇫🇮' },
  { value: 'fr', label: 'French', flag: '🇫🇷' },
  { value: 'fy', label: 'Frisian', flag: '🇳🇱' },
  { value: 'gl', label: 'Galician', flag: '🇪🇸' },
  { value: 'ka', label: 'Georgian', flag: '🇬🇪' },
  { value: 'de', label: 'German', flag: '🇩🇪' },
  { value: 'el', label: 'Greek', flag: '🇬🇷' },
  { value: 'gu', label: 'Gujarati', flag: '🇮🇳' },
  { value: 'ht', label: 'Haitian Creole', flag: '🇭🇹' },
  { value: 'ha', label: 'Hausa', flag: '🇳🇬' },
  { value: 'haw', label: 'Hawaiian', flag: '🇺🇸' },
  { value: 'iw', label: 'Hebrew', flag: '🇮🇱' },
  { value: 'hi', label: 'Hindi', flag: '🇮🇳' },
  { value: 'hmn', label: 'Hmong', flag: '🇨🇳' },
  { value: 'hu', label: 'Hungarian', flag: '🇭🇺' },
  { value: 'is', label: 'Icelandic', flag: '🇮🇸' },
  { value: 'ig', label: 'Igbo', flag: '🇳🇬' },
  { value: 'id', label: 'Indonesian', flag: '🇮🇩' },
  { value: 'ga', label: 'Irish', flag: '🇮🇪' },
  { value: 'it', label: 'Italian', flag: '🇮🇹' },
  { value: 'ja', label: 'Japanese', flag: '🇯🇵' },
  { value: 'jw', label: 'Javanese', flag: '🇮🇩' },
  { value: 'kn', label: 'Kannada', flag: '🇮🇳' },
  { value: 'kk', label: 'Kazakh', flag: '🇰🇿' },
  { value: 'km', label: 'Khmer', flag: '🇰🇭' },
  { value: 'rw', label: 'Kinyarwanda', flag: '🇷🇼' },
  { value: 'ko', label: 'Korean', flag: '🇰🇷' },
  { value: 'ku', label: 'Kurdish (Kurmanji)', flag: '🇹🇷' },
  { value: 'ky', label: 'Kyrgyz', flag: '🇰🇬' },
  { value: 'lo', label: 'Lao', flag: '🇱🇦' },
  { value: 'la', label: 'Latin', flag: '🇻🇦' },
  { value: 'lv', label: 'Latvian', flag: '🇱🇻' },
  { value: 'lt', label: 'Lithuanian', flag: '🇱🇹' },
  { value: 'lb', label: 'Luxembourgish', flag: '🇱🇺' },
  { value: 'mk', label: 'Macedonian', flag: '🇲🇰' },
  { value: 'mg', label: 'Malagasy', flag: '🇲🇬' },
  { value: 'ms', label: 'Malay', flag: '🇲🇾' },
  { value: 'ml', label: 'Malayalam', flag: '🇮🇳' },
  { value: 'manglish', label: 'Manglish', flag: '🇮🇳' },
  { value: 'mt', label: 'Maltese', flag: '🇲🇹' },
  { value: 'mi', label: 'Maori', flag: '🇳🇿' },
  { value: 'mr', label: 'Marathi', flag: '🇮🇳' },
  { value: 'mn', label: 'Mongolian', flag: '🇲🇳' },
  { value: 'my', label: 'Myanmar (Burmese)', flag: '🇲🇲' },
  { value: 'ne', label: 'Nepali', flag: '🇳🇵' },
  { value: 'no', label: 'Norwegian', flag: '🇳🇴' },
  { value: 'or', label: 'Odia (Oriya)', flag: '🇮🇳' },
  { value: 'ps', label: 'Pashto', flag: '🇦🇫' },
  { value: 'fa', label: 'Persian', flag: '🇮🇷' },
  { value: 'pl', label: 'Polish', flag: '🇵🇱' },
  { value: 'pt', label: 'Portuguese', flag: '🇧🇷' },
  { value: 'pa', label: 'Punjabi', flag: '🇮🇳' },
  { value: 'ro', label: 'Romanian', flag: '🇷🇴' },
  { value: 'ru', label: 'Russian', flag: '🇷🇺' },
  { value: 'sm', label: 'Samoan', flag: '🇼🇸' },
  { value: 'gd', label: 'Scots Gaelic', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { value: 'sr', label: 'Serbian', flag: '🇷🇸' },
  { value: 'st', label: 'Sesotho', flag: '🇱🇸' },
  { value: 'sn', label: 'Shona', flag: '🇿🇼' },
  { value: 'sd', label: 'Sindhi', flag: '🇵🇰' },
  { value: 'si', label: 'Sinhala', flag: '🇱🇰' },
  { value: 'sk', label: 'Slovak', flag: '🇸🇰' },
  { value: 'sl', label: 'Slovenian', flag: '🇸🇮' },
  { value: 'so', label: 'Somali', flag: '🇸🇴' },
  { value: 'es', label: 'Spanish', flag: '🇪🇸' },
  { value: 'su', label: 'Sundanese', flag: '🇮🇩' },
  { value: 'sw', label: 'Swahili', flag: '🇰🇪' },
  { value: 'sv', label: 'Swedish', flag: '🇸🇪' },
  { value: 'tg', label: 'Tajik', flag: '🇹🇯' },
  { value: 'ta', label: 'Tamil', flag: '🇮🇳' },
  { value: 'tt', label: 'Tatar', flag: '🇷🇺' },
  { value: 'te', label: 'Telugu', flag: '🇮🇳' },
  { value: 'th', label: 'Thai', flag: '🇹🇭' },
  { value: 'tr', label: 'Turkish', flag: '🇹🇷' },
  { value: 'tk', label: 'Turkmen', flag: '🇹🇲' },
  { value: 'uk', label: 'Ukrainian', flag: '🇺🇦' },
  { value: 'ur', label: 'Urdu', flag: '🇵🇰' },
  { value: 'ug', label: 'Uyghur', flag: '🇨🇳' },
  { value: 'uz', label: 'Uzbek', flag: '🇺🇿' },
  { value: 'vi', label: 'Vietnamese', flag: '🇻🇳' },
  { value: 'cy', label: 'Welsh', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { value: 'xh', label: 'Xhosa', flag: '🇿🇦' },
  { value: 'yi', label: 'Yiddish', flag: '🇮🇱' },
  { value: 'yo', label: 'Yoruba', flag: '🇳🇬' },
  { value: 'zu', label: 'Zulu', flag: '🇿🇦' }
];

export const DEMO_TEXTS = [
  ...GENERATED_DEMO_TEXTS,
  // HATE SPEECH
  { lang: 'en', category: 'hate_speech', text: "I hate people of your kind, you all deserve to be banned from this game forever." },
  { lang: 'en', category: 'hate_speech', text: "Your entire group is a cancer to this community. Get out." },
  { lang: 'en', category: 'hate_speech', text: "We don't want people like you here. Go back to where you came from." },
  { lang: 'en', category: 'hate_speech', text: "This server is for real players, not for sub-humans like you." },
  { lang: 'en', category: 'hate_speech', text: "I hope your entire kind gets wiped out. You are a disgrace." },
  { lang: 'en', category: 'hate_speech', text: "Disgusting behavior from a disgusting group of people." },
  { lang: 'en', category: 'hate_speech', text: "You are all inferior and shouldn't even be allowed to speak." },
  { lang: 'en', category: 'hate_speech', text: "The world would be better without your type." },
  { lang: 'en', category: 'hate_speech', text: "I refuse to play with anyone from your background." },
  { lang: 'en', category: 'hate_speech', text: "You people are the reason this game is dying." },

  // HARASSMENT
  { lang: 'en', category: 'harassment', text: "You are so stupid. I'm going to keep killing you every time you spawn. Quit the game." },
  { lang: 'en', category: 'harassment', text: "I'm going to follow you into every match and ruin your day." },
  { lang: 'en', category: 'harassment', text: "Stop playing. Nobody wants you here. Just leave." },
  { lang: 'en', category: 'harassment', text: "I'm going to report you every single day until you're banned." },
  { lang: 'en', category: 'harassment', text: "You're a loser. Why do you even bother waking up?" },
  { lang: 'en', category: 'harassment', text: "I'll make sure everyone on this server knows how pathetic you are." },
  { lang: 'en', category: 'harassment', text: "You can't hide from me. I'll find your alt accounts too." },
  { lang: 'en', category: 'harassment', text: "Keep talking and see what happens. I'm watching you." },
  { lang: 'en', category: 'harassment', text: "You're a waste of space. Do us all a favor and delete your account." },
  { lang: 'en', category: 'harassment', text: "I'm going to spam your inbox until you block me, then I'll find another way." },

  // PROFANITY
  { lang: 'en', category: 'profanity', text: "What the f*** is wrong with you? This is bulls***." },
  { lang: 'en', category: 'profanity', text: "Holy s***, you are absolutely terrible at this." },
  { lang: 'en', category: 'profanity', text: "F*** off and leave me alone." },
  { lang: 'en', category: 'profanity', text: "This game is f***ing broken. Fix your s*** developers." },
  { lang: 'en', category: 'profanity', text: "You're a f***ing idiot if you think that was a good play." },
  { lang: 'en', category: 'profanity', text: "S*** happens, but you're a constant disaster." },
  { lang: 'en', category: 'profanity', text: "Go f*** yourself, nobody cares about your opinion." },
  { lang: 'en', category: 'profanity', text: "D*** it, we lost because of your incompetence." },
  { lang: 'en', category: 'profanity', text: "You f***ing noob, learn to play or get out." },
  { lang: 'en', category: 'profanity', text: "B***h please, you couldn't hit a barn door." },

  // THREAT
  { lang: 'en', category: 'threat', text: "I know where you live. I'm going to find you and break your keyboard." },
  { lang: 'en', category: 'threat', text: "If I ever see you in real life, it's over for you." },
  { lang: 'en', category: 'threat', text: "I'm going to hack your account and delete everything." },
  { lang: 'en', category: 'threat', text: "Watch your back. You don't know who you're messing with." },
  { lang: 'en', category: 'threat', text: "I'll make sure you never play this game again, one way or another." },
  { lang: 'en', category: 'threat', text: "I'm coming for you. Sleep with one eye open." },
  { lang: 'en', category: 'threat', text: "You'll regret ever crossing me. I have your IP address." },
  { lang: 'en', category: 'threat', text: "I'm going to ruin your life. Just wait and see." },
  { lang: 'en', category: 'threat', text: "Consider this your final warning. Stop now or else." },
  { lang: 'en', category: 'threat', text: "I'll find a way to hurt you where it counts." },

  // RACISM
  { lang: 'en', category: 'racism', text: "Go back to your country, we don't want your race playing on our servers." },
  { lang: 'en', category: 'racism', text: "You people are all the same, lazy and incompetent." },
  { lang: 'en', category: 'racism', text: "I refuse to take orders from someone of your ethnicity." },
  { lang: 'en', category: 'racism', text: "Typical behavior for someone of your background." },
  { lang: 'en', category: 'racism', text: "Your race is the reason this world is in trouble." },
  { lang: 'en', category: 'racism', text: "I don't play with [racial slur]s. Get out of my lobby." },
  { lang: 'en', category: 'racism', text: "You're just a [racial slur], you'll never be as good as us." },
  { lang: 'en', category: 'racism', text: "Keep your [racial slur] culture out of our game." },
  { lang: 'en', category: 'racism', text: "I hope they build a wall to keep people like you out." },
  { lang: 'en', category: 'racism', text: "You're a disgrace to your race, and your race is a disgrace to humanity." },

  // BULLYING
  { lang: 'en', category: 'bullying', text: "You absolute trash player, your skill is non-existent. Go uninstall and stop wasting everyone's time you idiot." },
  { lang: 'en', category: 'bullying', text: "Look at this loser trying so hard. You'll never be good." },
  { lang: 'en', category: 'bullying', text: "Why are you even playing? You're just a burden to your team." },
  { lang: 'en', category: 'bullying', text: "Everyone is laughing at you. You're the joke of the server." },
  { lang: 'en', category: 'bullying', text: "You're so pathetic. I bet you have no friends in real life." },
  { lang: 'en', category: 'bullying', text: "Stop talking, your voice is annoying and your gameplay is worse." },
  { lang: 'en', category: 'bullying', text: "You're a failure at everything you do, including this game." },
  { lang: 'en', category: 'bullying', text: "Go cry to your mommy, little baby." },
  { lang: 'en', category: 'bullying', text: "You're so bad it's actually impressive. How do you even function?" },
  { lang: 'en', category: 'bullying', text: "Nobody likes you. Just quit already." },

  // SEXUAL CONTENT (Expanded)
  { lang: 'en', category: 'sexual_content', text: "I'm going to do inappropriate things to your mom tonight." },
  { lang: 'en', category: 'sexual_content', text: "Show me your [body part] or I'll report you." },
  { lang: 'en', category: 'sexual_content', text: "Want to see something hot? Add me on Discord." },
  { lang: 'en', category: 'sexual_content', text: "You sound like you'd be good in bed. Want to find out?" },
  { lang: 'en', category: 'sexual_content', text: "I'm getting [aroused] just thinking about you." },
  { lang: 'en', category: 'sexual_content', text: "Let's talk about something more... intimate." },
  { lang: 'en', category: 'sexual_content', text: "You're such a [sexual term], I bet you love it." },
  { lang: 'en', category: 'sexual_content', text: "I want to [explicit action] you so bad." },
  { lang: 'en', category: 'sexual_content', text: "Send me some nudes and I'll carry you to the next rank." },
  { lang: 'en', category: 'sexual_content', text: "You're a sexy little thing, aren't you?" },
  { lang: 'en', category: 'sexual_content', text: "I'm touching myself while watching you play." },
  { lang: 'en', category: 'sexual_content', text: "Let's have some fun in a private chat." },
  { lang: 'en', category: 'sexual_content', text: "You have a great [body part], I can tell." },
  { lang: 'en', category: 'sexual_content', text: "I'd love to get my hands on you." },
  { lang: 'en', category: 'sexual_content', text: "You're making me so [aroused] right now." },
  { lang: 'en', category: 'sexual_content', text: "Want to trade pics? I'll go first." },
  { lang: 'en', category: 'sexual_content', text: "I'm imagining you without any clothes on." },
  { lang: 'en', category: 'sexual_content', text: "You're such a tease, I love it." },
  { lang: 'en', category: 'sexual_content', text: "Let's do some roleplay, I'll be the master." },
  { lang: 'en', category: 'sexual_content', text: "I want to feel you all over me." },
  { lang: 'en', category: 'sexual_content', text: "You're a dirty little player, aren't you?" },
  { lang: 'en', category: 'sexual_content', text: "I bet you're a [sexual term] in real life." },
  { lang: 'en', category: 'sexual_content', text: "Let's take this to a private room." },
  { lang: 'en', category: 'sexual_content', text: "I'm thinking about your [body part] right now." },
  { lang: 'en', category: 'sexual_content', text: "You're so [arousing], I can't focus on the game." },
  { lang: 'en', category: 'sexual_content', text: "Want to do a cam show for me?" },
  { lang: 'en', category: 'sexual_content', text: "I'll pay you in skins if you show me your [body part]." },
  { lang: 'en', category: 'sexual_content', text: "You're a [sexual term], I can see it in your playstyle." },
  { lang: 'en', category: 'sexual_content', text: "I want to [explicit action] your [body part]." },
  { lang: 'en', category: 'sexual_content', text: "You're making me so hard right now." },
  { lang: 'en', category: 'sexual_content', text: "Let's get naked on voice chat." },
  { lang: 'en', category: 'sexual_content', text: "I'm going to [explicit action] you until you scream." },
  { lang: 'en', category: 'sexual_content', text: "You're a [sexual term] and you know it." },
  { lang: 'en', category: 'sexual_content', text: "I want to taste you." },
  { lang: 'en', category: 'sexual_content', text: "You're so [arousing], I'm losing my mind." },
  { lang: 'en', category: 'sexual_content', text: "Let's do something [explicit] together." },
  { lang: 'en', category: 'sexual_content', text: "I'm imagining your [body part] in my mouth." },
  { lang: 'en', category: 'sexual_content', text: "You're a [sexual term] and I'm going to punish you." },
  { lang: 'en', category: 'sexual_content', text: "I want to [explicit action] you from behind." },
  { lang: 'en', category: 'sexual_content', text: "You're making me so wet right now." },
  { lang: 'en', category: 'sexual_content', text: "Let's have some [explicit] fun." },
  { lang: 'en', category: 'sexual_content', text: "I'm thinking about your [body part] and it's making me [aroused]." },
  { lang: 'en', category: 'sexual_content', text: "You're such a [sexual term], I love how you play." },
  { lang: 'en', category: 'sexual_content', text: "I want to [explicit action] you all night long." },
  { lang: 'en', category: 'sexual_content', text: "You're so [arousing], I can't stop thinking about you." },
  { lang: 'en', category: 'sexual_content', text: "Let's do something [explicit] on the server." },
  { lang: 'en', category: 'sexual_content', text: "I'm imagining your [body part] and I'm [aroused]." },
  { lang: 'en', category: 'sexual_content', text: "You're a [sexual term] and I'm going to make you mine." },
  { lang: 'en', category: 'sexual_content', text: "I want to [explicit action] you until you can't walk." },
  { lang: 'en', category: 'sexual_content', text: "You're making me so [aroused], it's crazy." },

  // SPAM (Expanded)
  { lang: 'en', category: 'spam', text: "buy cheap gold at www.scamsite.com buy cheap gold buy cheap gold buy cheap gold" },
  { lang: 'en', category: 'spam', text: "FREE SKINS! CLICK HERE: http://bit.ly/fake-link FREE SKINS FREE SKINS" },
  { lang: 'en', category: 'spam', text: "JOIN MY CLAN! JOIN MY CLAN! JOIN MY CLAN! JOIN MY CLAN!" },
  { lang: 'en', category: 'spam', text: "SUBSCRIBE TO MY CHANNEL FOR GIVEAWAYS! SUBSCRIBE SUBSCRIBE SUBSCRIBE" },
  { lang: 'en', category: 'spam', text: "CHECK OUT MY STREAM! TWITCH.TV/SPAMMER CHECK OUT MY STREAM!" },
  { lang: 'en', category: 'spam', text: "WIN A NEW IPHONE! JUST ENTER YOUR EMAIL AT WWW.SCAM.COM" },
  { lang: 'en', category: 'spam', text: "NEED HELP RANKING UP? CHEAP BOOSTING SERVICES AT WWW.BOOST.ME" },
  { lang: 'en', category: 'spam', text: "VOTE FOR ME IN THE POPULARITY CONTEST! LINK IN BIO!" },
  { lang: 'en', category: 'spam', text: "GET 50% OFF ALL ITEMS! USE CODE: SPAM50 GET 50% OFF!" },
  { lang: 'en', category: 'spam', text: "LOOKING FOR A GIRLFRIEND? JOIN OUR DISCORD: DISCORD.GG/LONELY" },
  { lang: 'en', category: 'spam', text: "FREE COINS! FREE COINS! FREE COINS! FREE COINS! FREE COINS!" },
  { lang: 'en', category: 'spam', text: "JOIN OUR TOURNAMENT! PRIZES UP TO $1000! WWW.TOURNY.COM" },
  { lang: 'en', category: 'spam', text: "WANT TO BE A MOD? APPLY AT WWW.FAKE-MOD.COM" },
  { lang: 'en', category: 'spam', text: "GET UNLIMITED AMMO! DOWNLOAD OUR HACK AT WWW.HACKS.COM" },
  { lang: 'en', category: 'spam', text: "BEST DEALS ON SKINS! VISIT WWW.SKINS.COM NOW!" },
  { lang: 'en', category: 'spam', text: "JOIN OUR COMMUNITY! DISCORD.GG/COMMUNITY JOIN NOW!" },
  { lang: 'en', category: 'spam', text: "FREE GIFT CARDS! CLICK THE LINK: WWW.GIFTCARDS.COM" },
  { lang: 'en', category: 'spam', text: "WANT TO LEVEL UP FAST? BUY OUR GUIDE AT WWW.LEVELUP.COM" },
  { lang: 'en', category: 'spam', text: "JOIN OUR GIVEAWAY! WIN A NEW PC! WWW.PCGIVEAWAY.COM" },
  { lang: 'en', category: 'spam', text: "GET FREE V-BUCKS! JUST CLICK THE LINK! WWW.VBUCKS.COM" },

  // SARCASM
  { lang: 'en', category: 'sarcasm', text: "Oh wow, brilliant play there buddy. Did you learn to aim from a blindfolded potato?" },
  { lang: 'en', category: 'sarcasm', text: "I love how you consistently manage to be the first one to die every single round. It's truly a unique talent." },
  { lang: 'en', category: 'sarcasm', text: "Nice shot! I didn't know the sky was our primary target." },
  { lang: 'en', category: 'sarcasm', text: "Great job standing still while they shot you. Very tactical." },
  { lang: 'en', category: 'sarcasm', text: "Wow, you're a real genius. I'm sure that 1v5 charge was going to work." },
  { lang: 'en', category: 'sarcasm', text: "I'm so glad you're on our team. We definitely needed someone to help the enemy win." },
  { lang: 'en', category: 'sarcasm', text: "Your map awareness is incredible. You didn't even see the guy standing right in front of you." },
  { lang: 'en', category: 'sarcasm', text: "Thanks for the 'help'. I couldn't have died without you." },
  { lang: 'en', category: 'sarcasm', text: "You're doing amazing. If the goal was to lose, we'd be champions." },
  { lang: 'en', category: 'sarcasm', text: "I've never seen someone fail so spectacularly. It's almost beautiful." },

  // TRASH TALK
  { lang: 'en', category: 'trash_talk', text: "Get rekt! My grandma plays better than you. GG easy." },
  { lang: 'en', category: 'trash_talk', text: "Is this your first time playing? Because it looks like it." },
  { lang: 'en', category: 'trash_talk', text: "You're so bad, you make bots look like pro players." },
  { lang: 'en', category: 'trash_talk', text: "Sit down, you just got schooled." },
  { lang: 'en', category: 'trash_talk', text: "Imagine being this bad at a video game. Couldn't be me." },
  { lang: 'en', category: 'trash_talk', text: "Go back to the tutorial, you clearly missed something." },
  { lang: 'en', category: 'trash_talk', text: "You're a walking highlight reel for the other team." },
  { lang: 'en', category: 'trash_talk', text: "GG WP... for us. For you, it was just embarrassing." },
  { lang: 'en', category: 'trash_talk', text: "I've seen better aim from a stormtrooper." },
  { lang: 'en', category: 'trash_talk', text: "You're the reason your team is losing. Just facts." },

  // MANGLISH / MALAYALAM
  { lang: 'ml', category: 'bullying', text: "നിങ്ങൾ ഒരു മോശം കളിക്കാരനാണ്, പോയി ഗെയിം അൺഇൻസ്റ്റാൾ ചെയ്യുക." },
  { lang: 'manglish', category: 'bullying', text: "nee oru pottan aanu, poyi game uninstall cheyeda noob." },
  { lang: 'manglish', category: 'trash_talk', text: "enthina ingane kalikkunne? poyi vere enthelum pani nokkeda." },
  { lang: 'manglish', category: 'profanity', text: "poda patti, ninakkonnum kalikkan ariyeela." },
  { lang: 'manglish', category: 'harassment', text: "ninnne njan vidilla, eppozhum ninte purake undakum." },
  { lang: 'manglish', category: 'sexual_content', text: "ninte ammaye njan innu rathri kaanum." },

  // OTHER LANGUAGES
  { lang: 'es', category: 'trash_talk', text: "Eres una basura de jugador, no sirves para nada. Desinstala el juego idiota." },
  { lang: 'fr', category: 'sarcasm', text: "C'est fascinant de voir à quel point tu peux rater des tirs faciles. Un vrai talent." },
  { lang: 'hi', category: 'bullying', text: "तुम बहुत बुरे खिलाड़ी हो, गेम डिलीট कर दो बेवकूफ।" },
  { lang: 'ja', category: 'sarcasm', text: "素晴らしいエイムですね。目隠しでもしてるんですか？" },
  { lang: 'ru', category: 'trash_talk', text: "Изи катка, вы просто нубы. Учитесь играть." },
  { lang: 'ko', category: 'bullying', text: "너 진짜 쓰레기 플레이어다. 실력이 아예 없네. 당장 삭제해라 바보야." },
  { lang: 'zh', category: 'trash_talk', text: "你绝对是个垃圾玩家，毫无技术可言。赶紧卸载别浪费大家时间了，白痴。" },
  { lang: 'ar', category: 'trash_talk', text: "أنت لاعب قمامة تمامًا، مهاراتك غير موجودة. اذهب وقم بإلغاء تثبيت اللعبة ولا تضيع وقت الجميع أيها الأحمق." },
  { lang: 'pt', category: 'trash_talk', text: "Você é um jogador lixo, sua habilidade não existe. Desinstala o jogo e para de perder nosso tempo, idiota." }
];

export const THEME = {
  cyan: '#00f3ff',
  purple: '#bc13fe',
  blue: '#0066ff',
  red: '#ff0055',
  green: '#00ff99',
  orange: '#ff9900',
  bgDark: '#050714',
};
